create table if not exists public.push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  token text not null unique,
  platform text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.push_tokens enable row level security;

drop policy if exists "Users can view their own push tokens"
on public.push_tokens;
create policy "Users can view their own push tokens"
on public.push_tokens for select to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Users can create their own push tokens"
on public.push_tokens;
create policy "Users can create their own push tokens"
on public.push_tokens for insert to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "Users can update their own push tokens"
on public.push_tokens;
create policy "Users can update their own push tokens"
on public.push_tokens for update to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

drop policy if exists "Users can delete their own push tokens"
on public.push_tokens;
create policy "Users can delete their own push tokens"
on public.push_tokens for delete to authenticated
using (user_id = (select auth.uid()));

grant select, insert, update, delete
on public.push_tokens to authenticated;
grant usage, select
on sequence public.push_tokens_id_seq to authenticated;

notify pgrst, 'reload schema';
